### ISSUE TITLE
DataTable cannot eat its own dog food???

### ISSUE THREAD

**Issue by VagyokC4** [MikeStall/DataTable#37]
Ok, so I took a standard XLSX file and saved each worksheet into a csv file.

```Javascript
	var dt = DataAccess.DataTable.New.ReadExcelAllSheets("sample.xlsx");
	dt.First (d => d.Name == "Products").SaveCSV("Products.csv");
	dt.First (d => d.Name == "Prices").SaveCSV("Prices.csv");
```

Then i tried to read them back in:
```Javascript
	var products = DataAccess.DataTable.New.ReadCsv("Products.csv");
	var prices = DataAccess.DataTable.New.ReadCsv("Prices.csv");
```

I get the error **unescaped double quote**

So I would have assumed since the content was readable in xlsx format, it would have written out the CSV in a correct format as to be able to read it back in.  But this is not the case.

How is it possible to have DataTable write CSV files that it can read?

**Comment by MikeStall** [comment]
What is the raw value of products.csv? 
If you submit a fix, I'll take the pull request.

**Comment by VagyokC4** [comment]
My guess is it has to do with the writing of the CSV file.  Perhaps implementing something like this would help.  Please keep in mind I have not looked into your codebase, but for pseduo-code if you want to handle special characters escaping in fields:

```Javascript
foreach (DataRow row in dt.Rows)
{
    IEnumerable<string> fields = row.ItemArray.Select(field => 
      string.Concat("\"", field.ToString().Replace("\"", "\"\""), "\""));
    sb.AppendLine(string.Join(",", fields));
}
```

**Comment by VagyokC4** [comment]
I believe this will do the trick.

Pull Request:  https://github.com/MikeStall/DataTable/pull/38

**Comment by MikeStall** [comment]
Resolved with pull request.
