### ISSUE TITLE
Read 'pipe' delineated files

### ISSUE THREAD

**Issue by VagyokC4** [MikeStall/DataTable#39]
Forgive me, I haven't had a lot of time to go through your code:

Is there an easy way to read pipe '|' separated files?  or an easy way to tell the reader what delineation should be used with it defaulting to comma?

**Comment by VagyokC4** [comment]
Ok,

I tried loading a 'pipe' delineated file and it loaded up just fine as expected.  Maybe the documentation can state this somewhere for others just finding this awesome tool.

**Comment by MikeStall** [comment]
By default, it automatically detects the separator from a well known list.
