### ISSUE TITLE
Map column names for RowAs<T> method?

### ISSUE THREAD

**Issue by VagyokC4** [MikeStall/DataTable#40]
Do we have a way to "Map" columns to strongly type properties when using RowAs<T> methods?

For example, I have a column "Index #" that should map to property "IndexNum" when using RowAs<T>() method?

If not, where do you think is the best place to put this type of logic?  Basically we need to pass in a Dictionary<string,string> into the RowAs<T> method so that if present we can do a lookup and ensure the data gets mapped correctly.

**Comment by VagyokC4** [comment]
Created in pull request : https://github.com/MikeStall/DataTable/pull/41

**Comment by MikeStall** [comment]
Fixed with pull request #41
