### ISSUE TITLE
ReadLazy Doesn't Return Rows Ending With Empty Value or Space

### ISSUE THREAD

**Issue by bgribaudo** [MikeStall/DataTable#44]
When run against CsvTools 1.0.11 from nuget, the below tests fail. For some reason, the fact that a row ends in a space or empty value confuses DataTable.

        [TestMethod]
        public void EndsWithEmptyValue()
        {
            var csv = @"Field1,Field2\nValue1,";
            var table = DataTable.New.ReadLazy(new MemoryStream(Encoding.UTF8.GetBytes(csv)));
            Assert.AreEqual(1, table.Rows.Count());
        }

        [TestMethod]
        public void EndsWithSpaceValue()
        {
            var csv = @"Field1,Field2\nValue1, ";
            var table = DataTable.New.ReadLazy(new MemoryStream(Encoding.UTF8.GetBytes(csv)));
            Assert.AreEqual(1, table.Rows.Count());
        }

**Comment by bgribaudo** [comment]
Here's an xUnit test for your DataTableTests.DataTableTests that shows the problem:
```
       [Fact]
        public void StreamReaderRowEndingWithEmptyValue()
        {
            // Arrange
            Stream s = new MemoryStream();
            TextWriter tw = new StreamWriter(s);
            tw.Write(
@"value1,value2
10,");
            tw.Flush();
            s.Position = 0;


            // Act

            DataTable dt = DataTable.New.ReadLazy(s);

            var x = dt.Rows.ToArray();

            // assert
            Assert.Equal(1, x.Length);
            Assert.Equal("10", x[0]["value1"]);
            Assert.Equal("", x[1]["value2"]);

            s.Position = 0; // verify stream is not disposed            
        }
```

**Comment by MikeStall** [comment]
Thanks - I'll take a look. (Or if you'd like to look and submit a pull request, that's even better :) )

**Comment by CVertex** [comment]
+1

Sorry, wish I had time to make a PR for this right now..

**Comment by MikeStall** [comment]
I can confirm the repro... thanks for the unit test. taking a look...

**Comment by MikeStall** [comment]
Fix pushed to master.

**Comment by bgribaudo** [comment]
Thanks much, Mike!
